# Site settings
title: Guilherme Garnier
description: Desenvolvimento de software e Open Source
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: guilhermgarnier
github_username: ggarnier
permalink: /:year/:month/:title/

# Build settings
markdown: redcarpet

# Default settings
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
