# Site settings
title: Guilherme Garnier
description: My random thoughts on software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.guilhermegarnier.com" # the base hostname & protocol for your site
avatar:

# Default settings
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

#
# Icons
#
icons:
  rss: true
  email:
  github: ggarnier
  bitbucket:
  twitter: guilhermgarnier
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: /:year/:month/:title/

#
# Scripts.
#
google_analytics: UA-25495907-1
disqus: ggarnier

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 5

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: true
ogp:
  image_url:
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
