#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: http://blog.guilhermegarnier.com
baseurl:
title: Guilherme Garnier
description: My random thoughts on software
avatar:
# language: ja
language: en
encoding: utf-8

# Default settings
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

#
# Icons
#
icons:
  rss: true
  email:
  github: ggarnier
  bitbucket:
  twitter: guilhermgarnier
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: /:year/:month/:title/

#
# Scripts.
#
google_analytics: UA-25495907-1
disqus: ggarnier

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 5

#
# Pagination.
#
paginate: 5
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: true
  facebook: true   # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: http://qckanemoto.github.io/jekyll-qck-theme/assets/img/ogp.png
  fb:
    admin: # facebook admin id
    app_id: 1743274505884984 # facebook application id

#
# Gems.
#
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
